### ISSUE TITLE
NOT WORKING 

### ISSUE THREAD

**Issue by krivadna** [truocphan/XSS-Checker#2]
~/XSS-Checker $ XSS-Checker --url https://help.netflix.com/en/search?q=

██╗  ██╗███████╗███████╗       ██████╗██╗  ██╗███████╗ ██████╗██╗  ██╗███████╗██████╗
╚██╗██╔╝██╔════╝██╔════╝      ██╔════╝██║  ██║██╔════╝██╔════╝██║ ██╔╝██╔════╝██╔══██╗
 ╚███╔╝ ███████╗███████╗█████╗██║     ███████║█████╗  ██║     █████╔╝ █████╗  ██████╔╝
 ██╔██╗ ╚════██║╚════██║╚════╝██║     ██╔══██║██╔══╝  ██║     ██╔═██╗ ██╔══╝  ██╔══██╗
██╔╝ ██╗███████║███████║      ╚██████╗██║  ██║███████╗╚██████╗██║  ██╗███████╗██║  ██║
╚═╝  ╚═╝╚══════╝╚══════╝       ╚═════╝╚═╝  ╚═╝╚══════╝ ╚═════╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝
                               v22.12.01 by Truoc Phan ( @truocphan )

>>>>>>>>>>>>>>>>>>>>>>> https://www.buymeacoffee.com/truocphan <<<<<<<<<<<<<<<<<<<<<<<

 [+] Discord:  https://discord.gg/2GTZKwN
 [+] Facebook: https://www.facebook.com/292706121240740
 [+] Twitter:  https://twitter.com/truocphan
 [+] Github:   https://github.com/truocphan
 [+] Gmail:    truocphan112017@gmail.com

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/XSS-Checker", line 8, in <module>
    sys.exit(vFaT3_jrF1FN30CA_o46KQ432mUyxGsUjjQqkXNFQzO0iHoX())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/XSS_Checker/__init__.py", line 52, in vFaT3_jrF1FN30CA_o46KQ432mUyxGsUjjQqkXNFQzO0iHoX
    eval(compile(r3tQ9Xk_pwg8nLTV.b64decode(eval('\x74\x72\x75\x73\x74')),'<string>','exec'))
  File "<string>", line 111, in <module>
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 90, in start
    self._start_process(self.path)
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/selenium/webdriver/common/service.py", line 198, in _start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/data/data/com.termux/files/usr/lib/python3.11/subprocess.py", line 1951, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/data/data/com.termux/files/home/.wdm/drivers/chromedriver/linux64/114.0.5735/chromedriver'
~/XSS-Checker $

**Comment by Gucci-Tech** [comment]
You need to provide it with the latest Chrome driver, at the time of this writing it is: https://storage.googleapis.com/chrome-for-testing-public/127.0.6533.88/win64/chromedriver-win64.zip

Then you extract and pass the driver to the script like so: 
`XSS-Checker --url https://www.site.com/ --driver C:\Users\Administrator\Downloads\chromedriver-win64\chromedriver.exe`
